version: '3'
services:          
    ##mysql:
    #    image: mysql:5.7
    #    restart: on-failure
    #    networks: 
    #        - production-network
    #    environment:
    #        MYSQL_ROOT_PASSWORD: 'root'
    #        MYSQL_DATABASE: 'petshop'
    #        MYSQL_USER: 'admin'
    #        MYSQL_PASSWORD: 'admin'
    #
    #    ports:
    #        - "3306:3306"
    #    volumes:
    #        - ./database:/var/lib/mysql      
    node1:
        build:
            dockerfile: ./docker/node.dockerfile
            context: .
        command: nodemon index.js
        volumes:
            - .:/app
        image: felipealrc/dockerized-node
        container_name: node1
        ports:
            - "3000:3000"
        networks:
            - production-network
    #    depends_on:
    #        - "mysql"
networks: 
    production-network:
        driver: bridge