version: '3'
services:            
    node1:
        build:
            dockerfile: ./docker/node.dockerfile
            context: .
        command: npm start
        volumes:
            - .:/app
        image: felipealrc/dockerized-node
        container_name: node1
        ports:
            - "3000:3000"
        networks:
            - production-network
networks: 
    production-network:
        driver: bridge